/*
 * Copyright (c) 2019, Pavel Dubrova <pashadubrova@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _DT_BINDINGS_CLK_MSM_GCC_8976_H
#define _DT_BINDINGS_CLK_MSM_GCC_8976_H

/* Hardware clocks */
#define GCC_XO				0
#define GCC_XO_A			1
#define GPLL0				2
#define GPLL2				3
#define GPLL3				4
#define GPLL4				5
#define GPLL6				6
#define GPLL0_OUT_MAIN			7
#define GPLL2_OUT_MAIN			8
#define GPLL3_OUT_MAIN			9
#define GPLL4_OUT_MAIN			10
#define GPLL6_OUT_MAIN			11
#define GPLL0_AO_OUT_MAIN		12

/* RCGs */
#define APS_0_CLK_SRC			13
#define APS_1_CLK_SRC			14
#define APSS_AHB_CLK_SRC		15
#define BLSP1_QUP1_I2C_APPS_CLK_SRC	16
#define BLSP1_QUP1_SPI_APPS_CLK_SRC	17
#define BLSP1_QUP2_I2C_APPS_CLK_SRC	18
#define BLSP1_QUP2_SPI_APPS_CLK_SRC	19
#define BLSP1_QUP3_I2C_APPS_CLK_SRC	20
#define BLSP1_QUP3_SPI_APPS_CLK_SRC	21
#define BLSP1_QUP4_I2C_APPS_CLK_SRC	22
#define BLSP1_QUP4_SPI_APPS_CLK_SRC	23
#define BLSP1_UART1_APPS_CLK_SRC	24
#define BLSP1_UART2_APPS_CLK_SRC	25
#define BLSP2_QUP1_I2C_APPS_CLK_SRC	26
#define BLSP2_QUP1_SPI_APPS_CLK_SRC	27
#define BLSP2_QUP2_I2C_APPS_CLK_SRC	28
#define BLSP2_QUP2_SPI_APPS_CLK_SRC	29
#define BLSP2_QUP3_I2C_APPS_CLK_SRC	30
#define BLSP2_QUP3_SPI_APPS_CLK_SRC	31
#define BLSP2_QUP4_I2C_APPS_CLK_SRC	32
#define BLSP2_QUP4_SPI_APPS_CLK_SRC	33
#define BLSP2_UART1_APPS_CLK_SRC	34
#define BLSP2_UART2_APPS_CLK_SRC	35
#define CAMSS_GP0_CLK_SRC		36
#define CAMSS_GP1_CLK_SRC		37
#define CAMSS_TOP_AHB_CLK_SRC		38
#define CCI_CLK_SRC			39
#define CPP_CLK_SRC			40
#define CRYPTO_CLK_SRC			41
#define CSI0_CLK_SRC			42
#define CSI1_CLK_SRC			43
#define CSI2_CLK_SRC			44
#define CSI0PHYTIMER_CLK_SRC		45
#define CSI1PHYTIMER_CLK_SRC		46
#define GP1_CLK_SRC			47
#define GP2_CLK_SRC			48
#define GP3_CLK_SRC			49
#define JPEG0_CLK_SRC			50
#define MCLK0_CLK_SRC			51
#define MCLK1_CLK_SRC			52
#define MCLK2_CLK_SRC			53
#define PDM2_CLK_SRC			54
#define RBCPR_GFX_CLK_SRC		55
#define SDCC1_APPS_CLK_SRC		56
#define SDCC1_ICE_CORE_CLK_SRC		57
#define SDCC2_APPS_CLK_SRC		58
#define SDCC3_APPS_CLK_SRC		59
#define VCODEC0_CLK_SRC			60
#define VFE0_CLK_SRC			61
#define VFE1_CLK_SRC			62
#define USB_FS_IC_CLK_SRC		63
#define USB_FS_SYSTEM_CLK_SRC		64
#define USB_HS_SYSTEM_CLK_SRC		65

/* Branches */
#define GCC_APS_0_CLK			66
#define GCC_APS_1_CLK			67
#define GCC_APPS_AHB_CLK		68
#define GCC_APPS_AXI_CLK		69
#define GCC_APSS_TCU_CLK		70
#define GCC_BLSP1_AHB_CLK		71
#define GCC_BLSP2_AHB_CLK		72
#define GCC_BLSP1_QUP1_SPI_APPS_CLK	73
#define GCC_BLSP1_QUP1_I2C_APPS_CLK	74
#define GCC_BLSP1_QUP2_I2C_APPS_CLK	75
#define GCC_BLSP1_QUP2_SPI_APPS_CLK	76
#define GCC_BLSP1_QUP3_I2C_APPS_CLK	77
#define GCC_BLSP1_QUP3_SPI_APPS_CLK	78
#define GCC_BLSP1_QUP4_I2C_APPS_CLK	79
#define GCC_BLSP1_QUP4_SPI_APPS_CLK	80
#define GCC_BLSP1_UART1_APPS_CLK	81
#define GCC_BLSP1_UART2_APPS_CLK	82
#define GCC_BLSP2_QUP1_I2C_APPS_CLK	83
#define GCC_BLSP2_QUP1_SPI_APPS_CLK	84
#define GCC_BLSP2_QUP2_I2C_APPS_CLK	85
#define GCC_BLSP2_QUP2_SPI_APPS_CLK	86
#define GCC_BLSP2_QUP3_I2C_APPS_CLK	87
#define GCC_BLSP2_QUP3_SPI_APPS_CLK	88
#define GCC_BLSP2_QUP4_I2C_APPS_CLK	89
#define GCC_BLSP2_QUP4_SPI_APPS_CLK	90
#define GCC_BLSP2_UART1_APPS_CLK	91
#define GCC_BLSP2_UART2_APPS_CLK	92
#define GCC_BOOT_ROM_AHB_CLK		93
#define GCC_CAMSS_AHB_CLK		94
#define GCC_CAMSS_CCI_AHB_CLK		95
#define GCC_CAMSS_CCI_CLK		96
#define GCC_CAMSS_CPP_AHB_CLK		97
#define GCC_CAMSS_CPP_AXI_CLK		98
#define GCC_CAMSS_CPP_CLK		99
#define GCC_CAMSS_CSI0_AHB_CLK		100
#define GCC_CAMSS_CSI0_CLK		101
#define GCC_CAMSS_CSI0PHY_CLK		102
#define GCC_CAMSS_CSI0PIX_CLK		103
#define GCC_CAMSS_CSI0RDI_CLK		104
#define GCC_CAMSS_CSI1_AHB_CLK		105
#define GCC_CAMSS_CSI1_CLK		106
#define GCC_CAMSS_CSI1PHY_CLK		107
#define GCC_CAMSS_CSI1PIX_CLK		108
#define GCC_CAMSS_CSI1RDI_CLK		109
#define GCC_CAMSS_CSI2_AHB_CLK		110
#define GCC_CAMSS_CSI2_CLK		111
#define GCC_CAMSS_CSI2PHY_CLK		112
#define GCC_CAMSS_CSI2PIX_CLK		113
#define GCC_CAMSS_CSI2RDI_CLK		114
#define GCC_CAMSS_CSI_VFE0_CLK		115
#define GCC_CAMSS_CSI_VFE1_CLK		116
#define GCC_CAMSS_CSI0PHYTIMER_CLK	117
#define GCC_CAMSS_CSI1PHYTIMER_CLK	118
#define GCC_CAMSS_GP0_CLK		119
#define GCC_CAMSS_GP1_CLK		120
#define GCC_CAMSS_ISPIF_AHB_CLK		121
#define GCC_CAMSS_JPEG0_CLK		122
#define GCC_CAMSS_JPEG_AHB_CLK		123
#define GCC_CAMSS_JPEG_AXI_CLK		124
#define GCC_CAMSS_MCLK0_CLK		125
#define GCC_CAMSS_MCLK1_CLK		126
#define GCC_CAMSS_MCLK2_CLK		127
#define GCC_CAMSS_MICRO_AHB_CLK		128
#define GCC_CAMSS_TOP_AHB_CLK		129
#define GCC_CAMSS_VFE0_CLK		130
#define GCC_CAMSS_VFE_AHB_CLK		131
#define GCC_CAMSS_VFE_AXI_CLK		132
#define GCC_CAMSS_VFE1_CLK		133
#define GCC_CAMSS_VFE1_AHB_CLK		134
#define GCC_CAMSS_VFE1_AXI_CLK		135
#define GCC_CPP_TBU_CLK			136
#define GCC_CRYPTO_AHB_CLK		137
#define GCC_CRYPTO_AXI_CLK		138
#define GCC_CRYPTO_CLK			139
#define GCC_DCC_CLK			140
#define GCC_FS_SYSTEM_CLK		141
#define GCC_GP1_CLK			142
#define GCC_GP2_CLK			143
#define GCC_GP3_CLK			144
#define GCC_JPEG_TBU_CLK		145
#define GCC_MSS_CFG_AHB_CLK		146
#define GCC_MSS_Q6_BIMC_AXI_CLK		147
#define GCC_PDM_AHB_CLK			148
#define GCC_PDM2_CLK			149
#define GCC_PRNG_AHB_CLK		150
#define GCC_RBCPR_GFX_AHB_CLK		151
#define GCC_RBCPR_GFX_CLK		152
#define GCC_SDCC1_AHB_CLK		153
#define GCC_SDCC1_APPS_CLK		154
#define GCC_SDCC1_ICE_CORE_CLK		155
#define GCC_SDCC2_AHB_CLK		156
#define GCC_SDCC2_APPS_CLK		157
#define GCC_SDCC3_AHB_CLK		158
#define GCC_SDCC3_APPS_CLK		159
#define GCC_SMMU_CFG_CLK		160
#define GCC_USB2A_PHY_SLEEP_CLK		161
#define GCC_USB_HS_PHY_CFG_AHB_CLK	162
#define GCC_USB_FS_AHB_CLK		163
#define GCC_USB_FS_IC_CLK		164
#define GCC_USB_HS_AHB_CLK		165
#define GCC_USB_HS_SYSTEM_CLK		166
#define GCC_VENUS0_AHB_CLK		167
#define GCC_VENUS0_AXI_CLK		168
#define GCC_VENUS0_CORE0_VCODEC0_CLK	169
#define GCC_VENUS0_CORE1_VCODEC0_CLK	170
#define GCC_VENUS0_VCODEC0_CLK		171
#define GCC_VENUS_1_TBU_CLK		172
#define GCC_VENUS_TBU_CLK		173
#define GCC_VFE1_TBU_CLK		174
#define GCC_VFE_TBU_CLK			175

/* Resets */
#define GCC_CAMSS_MICRO_BCR		176
#define GCC_QUSB2_PHY_BCR		177
#define GCC_USB_HS_BCR			178
#define GCC_USB2_HS_PHY_ONLY_BCR	179

/* Dummy clocks */
#define WCNSS_M_CLK			180

#endif
